version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    deploy:
      placement:
        constraints:
          - node.labels.storage == true
      resources:
        limits:
          cpus: '2'
          memory: 2G
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - shared_storage:/var/www/html/data
    networks:
      - homelab
      - database

volumes:
  nextcloud_data:
  nextcloud_apps:
  nextcloud_config:
  shared_storage:
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,rw
      device: ":/volume1/shared"

networks:
  homelab:
    external: true
  database:
    external: true
