version: '3.8'

services:
  gitea:
    image: gitea/gitea:latest
    deploy:
      placement:
        constraints:
          - node.labels.development == true
      resources:
        limits:
          cpus: '1'
          memory: 1G
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${GITEA_DB_NAME:-gitea}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    volumes:
      - gitea_data:/data
    networks:
      - homelab
      - database

  jenkins:
    image: jenkins/jenkins:lts
    deploy:
      placement:
        constraints:
          - node.labels.development == true
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - homelab

volumes:
  gitea_data:
  jenkins_data:

networks:
  homelab:
    external: true
  database:
    external: true
