version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../configs/traefik.yml:/traefik.yml:ro
      - ../secrets/acme.json:/acme.json
    networks:
      - homelab

  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - homelab

networks:
  homelab:
    external: true

volumes:
  portainer_data:
