version: "3.8"

services:
  # File Storage & Sync
  nextcloud:
    image: nextcloud:apache
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud_db_pass
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: adminpass
    volumes:
      - nextcloud_data:/var/www/html
      - personal_storage:/var/www/html/data

  nextcloud-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud_db_pass
    volumes:
      - nextcloud_db:/var/lib/mysql

  # Document Management
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PAPERLESS_URL: http://localhost:8000
      PAPERLESS_SECRET_KEY: paperless_secret
      PAPERLESS_REDIS: redis://paperless-redis:6379
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - paperless_export:/usr/src/paperless/export
      - documents_inbox:/usr/src/paperless/consume

  paperless-redis:
    image: redis:6
    volumes:
      - paperless_redis:/data


volumes:
  nextcloud_data:
  nextcloud_db:
  personal_storage:
  paperless_data:
  paperless_media:
  paperless_export:
  paperless_redis:
  documents_inbox:
